spring:
  application:
    name: demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.JtaPlatform
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: jw
  h2:
    console.enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Google-Client-ID
            client-secret: Google-Client-Secret
            scope:
              - email
              - profile
jwt:
  issuer: 2e40camn@gmail.com
  secret_key: study-springboot